array_width = 90
chain_width = 160
edition = "2021"
fn_args_layout = "Tall"
fn_call_width = 120
hard_tabs = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 160
newline_style = "Unix"
reorder_imports = true
