/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ppaass_agent_activity_JniTest */

#ifndef _Included_com_ppaass_agent_activity_JniTest
#define _Included_com_ppaass_agent_activity_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ppaass_agent_activity_JniTest
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ppaass_agent_activity_JniTest_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
